# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  BIN_NAME: mdlp
  GCFLAGS: all="-B -l"
  LDFLAGS: -s -w -extldflags "-static"
  LDFLAGS_GUI: -s -w -H windowsgui -extldflags "-static"

tasks:
  default:
    cmds:
      - task: build:win
  build:win:
    #dir: src
    env:
      GOARCH: amd64
      GOOS: windows
      PATH: "E:\\WinLibs\\bin;{{ env \"PATH\" }}"
      WEBVIEW_USE_BUILTIN_MSWEBVIEW2: 1
    cmds:
      - task: format
      - task: manifest:win
      - go build -o {{.BIN_NAME}}.exe -trimpath -ldflags='{{.LDFLAGS_GUI}}' -gcflags={{.GCFLAGS}} -v
      - task: cleanup
  cleanup:
    cmds:
      #- coreutils rm rsrc_*.syso
      - rm rsrc_*.syso
  dev:win:
    #dir: src
    env:
      GOARCH: amd64
      GOOS: windows
      PATH: "E:\\WinLibs\\bin;{{ env \"PATH\" }}"
      WEBVIEW_USE_BUILTIN_MSWEBVIEW2: 1
    cmds:
      - task: format
      - task: manifest:win
      - go build -o {{.BIN_NAME}}.exe -trimpath -ldflags='{{.LDFLAGS}}' -gcflags={{.GCFLAGS}} -v
      - task: cleanup
  manifest:win:
    vars:
      GOARCH: amd64
      GOOS: windows
    cmds:
      # This doesn't use 'winres.json' because it won't work anyway.
      - go install github.com/tc-hib/go-winres@latest
      - go-winres simply --icon resource/windows/icon.png --manifest gui --product-name "Markdown Live Preview"
  format:
    #dir: src
    cmds:
      - gofmt -s -w .
